name: wuchuheng_ui_notice_bar
description: a notice bar for flutter ui
version: 0.0.1
homepage: https://github.com/wuchuheng/ui_notice_bar_dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 flutter:
   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
